name: "Build & Release Workflow"

on:
  pull_request:
    branches:
      - master
      - dev
      - test
  push:
    branches:
      - master
      - dev
      - test
  release:
    types:
      - created

jobs:
  check:
    name: "Code Health Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build_and_release:
    name: "Build and Release"
    runs-on: ubuntu-latest
    needs: [ check ]
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/carnet_prise.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "release-apk"
          path: build/app/outputs/flutter-apk/carnet_prise.apk